hide first-setup user before logging out

diff --git a/vanilla_first_setup/scripts/remove-first-setup-user b/vanilla_first_setup/scripts/remove-first-setup-user
--- a/vanilla_first_setup/scripts/remove-first-setup-user
+++ b/vanilla_first_setup/scripts/remove-first-setup-user
@@ -10,4 +10,6 @@ if ! [ "$UID" == "0" ]; then
     exit 6
 fi
 
+echo -e '[User]\nSession=firstsetup\nSystemAccount=true' > /var/lib/AccountsService/users/$(id -nu $PKEXEC_UID || echo invaliduser)
+systemctl restart accounts-daemon.service
 systemctl enable remove-first-setup-user.service
